spring:
  application:
    name: padong-be

  datasource:
    url: jdbc:mysql://padong-database.cpa0ggqay2hd.ap-northeast-2.rds.amazonaws.com:3306/padong
    username: padong
    password: vkehd2025
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true